# Generated by Django 5.2.11 on 2026-03-10 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_coupon_cart_coupon'),
        ('catalog', '0002_alter_brand_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='catalog.brand'),
        ),
    ]
