# Generated by Django 5.2.11 on 2026-03-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_coupon_brand'),
        ('catalog', '0002_alter_brand_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'variant')},
        ),
    ]
